#!/bin/sh

test -n "$2" || {
  echo "Usage: $0 <table> <z>" >&2
  exit 1
}

dir=`dirname $0`
table="$1"; shift
zoom="$1"; shift

simp=false
clip=false
grid=false

while test -n "$1"; do
  if test "$1" = "simp"; then
    simp=true
  elif test "$1" = "clip"; then
    clip=true
  elif test "$1" = "grid"; then
    grid=true
  else
    echo "Unsupported argument $1" >&2
  fi
  shift
done

gf="the_geom_webmercator" # TODO: read from template.xml
expr=''
if test "$clip" = 'true'; then
  expr='ST_ClipByBox2D('$gf', !bbox!)'
fi
if test "$grid" = 'true'; then
  expr='ST_SnapToGrid('$expr', greatest(!pixel_height!,!pixel_width!)/20.0)'
fi
if test "$simp" = 'true'; then
  expr='ST_Simplify('$expr', greatest(!pixel_height!,!pixel_width!)/20.0)'
fi
tabexpr="( SELECT ${expr} ${gf} FROM ${table} WHERE ${gf} && "'!bbox! ) bar'

# escape table expression
tabexpr=`echo "${tabexpr}" | sed -e 's/[\/&]/\\\\&/g'`

echo "table:${table} zoom:${zoom} simp:${simp} clip:${clip}" >&2
#echo "tabexpr:${tabexpr}" >&2

#exit 1

tile=`$dir/tile ${zoom}`
cat ${dir}/template.xml | sed \
  -e "s/@TABLE@/${tabexpr}/" \
  -e "s/@TILE@/${tile}/" \

: \
  -e "s/@EXPR@/${expr}/" \
  -e "s/@GRID@/${grid}/" \
  -e "s/@SIMP@/${simp}/" \
  -e "s/@CLIP@/${clip}/"
